<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/11 04:26:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=web;host=127.0.0.1',
  'profiler' => false,
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
