<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/09/11 01:33:13
sfConfig::add(array(
  'mod_ticketsreports_enabled' => true,
  'mod_ticketsreports_view_class' => 'sfPHP',
));
