<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/09/10 23:54:48
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
