<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/09/10 23:58:14
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
