<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/09/11 01:33:12
sfConfig::add(array(
  'mod_discussionsreports_enabled' => true,
  'mod_discussionsreports_view_class' => 'sfPHP',
));
